### ISSUE TITLE
ESM compatibility

### ISSUE THREAD

**Issue by v1rtl** [sossejs/sosse#4]
Hello, while making a simple dev server I noticed that Sosse still uses `require`, even in the ESM generated code

![image](https://user-images.githubusercontent.com/35937217/87707514-e72b5a80-c7a9-11ea-9707-561d007fe863.png)

Node disallows using `require` in the ESM module. So it should be imported in the top so it properly builds to `import chokidar from 'chokidar'`

The full stacktrace is this:

```
> node main.js
(node:240789) UnhandledPromiseRejectionWarning: ReferenceError: require is not defined
    at _temp2 (file:///home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/sosse@0.6.0/node_modules/sosse/dist/main.mjs:862:26)
    at _temp4 (file:///home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/sosse@0.6.0/node_modules/sosse/dist/main.mjs:885:57)
    at hsr (file:///home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/sosse@0.6.0/node_modules/sosse/dist/main.mjs:907:74)
    at file:///home/v1rtl/Coding/tinyhttp/examples/dev-server/main.js:4:1
    at ModuleJob.run (internal/modules/esm/module_job.js:140:23)
    at async Loader.import (internal/modules/esm/loader.js:162:24)
```

Sosse version: 0.6.0
Node version: 14.5.0

**Comment by katywings** [comment]
@talentlessguy Tbh. those requires cannot be moved to the top of sosse. They have to be called dynamically after file changes - thats the essential part for the hot server reload ;). 

Maybe there is a chance to switch to dynamic imports, but this is not something I can quickly change, I have to test this in the very detail of each require ^^.

**Comment by v1rtl** [comment]
@katywings oh ok, no worries. I could maybe try to find the way to load CJS version of Sosse :thinking:

**Comment by katywings** [comment]
@talentlessguy I investigated this and in the end got stuck in an upstream blocker :facepalm:

Hot module replace currently is only possible with `require`, the ("type": "module") `import` cache cannot be invalidated. 

This is the corresponding upstream issue: nodejs/node#49442

---

I gonna watch that upstream issue but ESM support has to unfortunately wait for now :see_no_evil:

**Comment by katywings** [comment]
Also something that should be watched going forward nodejs/node#49452.
